AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an S3 bucket for our CICD

Parameters:
  EnvironmentName:
    Type: String
    Default: test
    AllowedValues:
      - test
      - staging
      - production

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::StackName}-${EnvironmentName}-bucket'
      Tags:
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Environment
          Value: GitHubActionsTesting

Outputs:
  BucketName:
    Description: Name of the S3 bucket created
    Value: !Ref MyS3Bucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
